abstraction_buckets: 64
auto_hand_target: true
auto_resource_management: true
cfr_iterations: 2000
cfr_sampling_enabled: true
cpu_usage_limit: 95.0
default_table_type: cashgame
gpu_enabled: 1
gpu_memory_limit: 92.0
language: en
manual_risk_override: false
max_players: 9
nash_calculation_interval_ms: 25
ocr_confidence_threshold: 0.8
ocr_enabled: true
ocr_interval_ms: 25
ram_usage_limit: 85.0
risk_percentage: 75.0
screen_region:
  height: 1080
  width: 1920
  x: 0
  y: 0
show_probabilities: 1
show_recommendations: 1
show_statistics: 1
target_hands_per_100: 65
theme: dark
